# Generated by Django 6.1.1 on 2026-09-21 15:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('opening_time', models.TimeField(default=datetime.time(8, 0))),
                ('closing_time', models.TimeField(default=datetime.time(23, 59))),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('table_type', models.CharField(choices=[('common', 'Uliwmaliq'), ('cabin', 'Kabina')], default='common', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Bos'), ('reserved', 'Bron qilingan'), ('busyBant', 'Busy')], default='free', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'number')},
            },
        ),
    ]
