# Generated by Django 6.1.1 on 2026-09-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('free', 'Bos'), ('reserved', 'Bron qilingan'), ('busy', 'Bant')], default='free', max_length=20),
        ),
    ]
