# Generated by Django 6.1.1 on 2026-09-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('g', 'Gramm'), ('l', 'Litr'), ('ml', 'Millilitr'), ('piece', 'dana')], default='kg', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'name')},
            },
        ),
    ]
