# Generated by Django 6.1.1 on 2026-09-21 15:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(verbose_name='Baslaniw waqti')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200), help_text='Format: HH:MM:SS', verbose_name='Dawamliligi')),
                ('end_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Tamamlaniw waqti')),
                ('status', models.CharField(choices=[('pending', 'Kutilmekte'), ('booked', 'Bronlangan'), ('cancelled', 'Biykarlandi'), ('completed', 'Orinlandi')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='restaurants.table')),
            ],
        ),
    ]
